#!/bin/bash

echo $HOME/

export GIT_WORK_TREE=$HOME/code/
mkdir -p $HOME/code/
git checkout -f

export PLACK_ENV=deployment
export PERL_CPANM_OPT="-n -l ~/perl5/ --no-man-pages"
export PATH="$HOME/perl5/bin:$PATH";
export PERL5OPT="-Mlib=$HOME/perl5/lib/perl5/"

cd $HOME/code/
perl -I $HOME/perl5/lib/perl5/ -Mlocal::lib=$HOME/perl5/ /usr/local/bin/cpanm --notest --local-lib=~/perl5/ --installdeps .

if [ -x 'postinstall' ]; then
	./postinstall
fi

supervisorctl -c $HOME/supervisord.conf reread
supervisorctl -c $HOME/supervisord.conf update
supervisorctl -c $HOME/supervisord.conf restart all

